name: Build and Deploy to Azure
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: start-chat-app-az-openai    # Replace with your app name
  PYTHON_VERSION: '3.12'              # Adjust based on your Python version
  NODE_VERSION: '18'                  # Adjust based on your Node.js version

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Install and build frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build
          
      - name: Create deployment package
        run: |
          mkdir temp
          cp -r * temp/
          cd temp
          zip -r ../deploy.zip .
          
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Deploy Bicep template
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./infrastructure/main.bicep    # Adjust path to your bicep file
          failOnStdErr: false
          
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: deploy.zip