name: Build and Deploy to Azure
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: kjiaeqcesfvihbqwkusc    # Replace with your app name
  AZURE_RG_NAME: ohtgileknagladsnga
  PYTHON_VERSION: '3.12'              # Adjust based on your Python version
  NODE_VERSION: '18'                  # Adjust based on your Node.js version

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Container Registry Login
        uses: docker/login-action@v2
        with:
          # Container registry username
          username: ${{ secrets.DOCKER_USERNAME }}
          # Container registry password
          password: ${{ secrets.DOCKER_PASSWORD }}
          # Container registry server url
      - run: 'echo "${DOCKER_USERNAME}/${REPOSITORY_NAME}"
        shell: bash
      - uses: actions/checkout@v3
      - name: Build and Push Docker image
        run: |
          IMAGE_NAME="${DOCKER_USERNAME}/${REPOSITORY_NAME}"          
          docker build . --file WebApp.Dockerfile --tag ${IMAGE_NAME}:latest
          docker push ${IMAGE_NAME}:latest

      
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          resource-group-name: ${{ env.AZURE_RG_NAME }}
          images: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.REPOSITORY_NAME }}:latest