name: Docker Image Publish

on:
  push:
    branches: [ "main", "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v2
      with:
        # Container registry username
        username: ${{ secrets.ACR_USERNAME }}
        # Container registry password
        password: ${{ secrets.ACR_PASSWORD }}
        # Container registry server url
        login-server: ${{ secrets.ACR_SERVER }}
        
    - uses: actions/checkout@v3
    - name: Build and Push Docker image
      env:
        ACR_LOGIN_SERVER: ${{ secrets.ACR_SERVER }}
        REPOSITORY_NAME: ${{ secrets.REPOSITORY_NAME }}
      run: |
        # Build with ACR server and repository name
        IMAGE_NAME="${ACR_LOGIN_SERVER}/${REPOSITORY_NAME}"
        VERSION="$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER"
        
        docker build . --file WebApp.Dockerfile --tag ${IMAGE_NAME}:${VERSION}
        docker tag ${IMAGE_NAME}:${VERSION} ${IMAGE_NAME}:latest
        docker push ${IMAGE_NAME}:${VERSION}
        docker push ${IMAGE_NAME}:latest